name: Receive repository dispatch event from docker-coffea-base

on:
  repository_dispatch:
    types: [coffea-base]

jobs:
  check-version:
    runs-on: ubuntu-latest
    if: github.repository == 'coffeateam/docker-coffea-dask'

    steps:
      - uses: actions/checkout@v2
      - name: Update coffea version
        run: |
          old_image=$(grep FROM dask/Dockerfile)
          new_image="FROM ${{ github.event.client_payload.image_tag }}"
          sed -i "s#$old_image#$new_image#g" dask/Dockerfile
          python_fix_tag_string=$(echo $old_image | cut -d '-' -f 3)
          python_tag=$(grep FROM dask/Dockerfile | cut -d '-' -f 3)
          sed -i "s#$python_tag#$python_fix_tag_string#g" dask/Dockerfile
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update coffea-base version to ${{ github.event.client_payload.image_tag }}"
          title: "Update coffea-base version to ${{ github.event.client_payload.image_tag }}"
          reviewers: "oshadura"
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          branch: "upgrade-coffea-base-version"
          body: |
            A new docker-coffea-base version has been detected.
            Updated `Dockerfile`s to use `${{ github.event.client_payload.image_tag }}`.
